name: "FuseDrill"
description: "Automatic fuzzing/simulation testing for OpenAPIs"
author: "Martynas Pocius"
branding:
  icon: "zap"
  color: "green"

inputs:
  fuseDrillBaseAddress:
    description: "Base address of the FuseDrill API"
    required: true
    type: string
  fuseDrillOpenApiUrl:
    description: "OpenAPI URL for FuseDrill"
    required: true
    type: string
  fuseDrillTestAccountOAuthHeaderValue:
    description: "OAuth header value for test account"
    required: true
    type: string

permissions:
  contents: write  # Enables both read and write access to repository content
  id-token: write  # This is required for actions interacting with GitHub Packages

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      shell: bash  # Added shell specification

    - name: Pull FuseDrill Docker Image
      run: docker pull ghcr.io/martasp/fusedrill/fusedrill-cli:latest
      shell: bash  # Added shell specification

    - name: Run FuseDrill CLI in Docker
      run: |
         docker run --network host --rm \
          -e FUSEDRILL_BASE_ADDRESS="${{ inputs.fuseDrillBaseAddress }}" \
          -e FUSEDRILL_OPENAPI_URL="${{ inputs.fuseDrillOpenApiUrl }}" \
          -e FUSEDRILL_OAUTH_HEADER="${{ inputs.fuseDrillTestAccountOAuthHeaderValue }}" \
          -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
          -e SMOKE_FLAG="true" \
          -e GITHUB_REPOSITORY_OWNER="${{ github.repository_owner }}" \
          -e GITHUB_REPOSITORY="${{ github.repository }}" \
          -e GITHUB_HEAD_REF="${{ github.head_ref }}" \
          -e GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}" \
          ghcr.io/martasp/fusedrill/fusedrill-cli:latest
      shell: bash  # Added shell specification
